# ***NUMPY LIBRARY PRACTICE NOTES***
## **IMPORTING NUMPY LIBRARY**

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [3]:
# checking numpy version
print(np.__version__)

1.26.4


### Different ways of creating numpy arrays

In [4]:
#1. from python list and tuple
bytuple = np.array((1,2,3,3,4))
print(bytuple)

bylist = ([2,4,6,3,56,454])
print(bylist)

[1 2 3 3 4]
[2, 4, 6, 3, 56, 454]


In [5]:
# 2. USING THE RANGE FUNCTION
byrange_function = np.arange(1,50)
print(byrange_function)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [6]:
# 3. BY USING ZEROES AND ONCES

byzeroes = np.zeros(4)
byones = np.ones(5)
print("This is by ZEROES :",byzeroes)
print("This is by ONES:",byones)

This is by ZEROES : [0. 0. 0. 0.]
This is by ONES: [1. 1. 1. 1. 1.]


In [7]:
#4. BY USING LINESPACE 
bylinespace  = np.linspace(0,1,5) # here 5 is the number of values
print(bylinespace)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
# 5. BY USING RANDOM.RAND()
byrandom = np.random.rand(4,4)
print(byrandom)

[[0.74761118 0.06524972 0.34970182 0.99767943]
 [0.89544316 0.8513632  0.64536559 0.57456258]
 [0.65349821 0.4783448  0.96132031 0.2618652 ]
 [0.72424422 0.99053427 0.49377822 0.12877182]]


### **CREATING 3D ARRAYS**

In [9]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### **Using ndim**
**ndim --> its used to get the number of dimensions in an array and it returns the integer value**

In [10]:
a = np.array(43)
b= np.array([43,44,45])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[['k','r','i'],['s','h','n']]])
print(a,",the dimension is :",a.ndim,'\n')
print(b,",the dimension is :",b.ndim,'\n')
print(c,",the dimension is :",c.ndim,'\n')
print(d,",the dimension is :",d.ndim,'\n')

43 ,the dimension is : 0 

[43 44 45] ,the dimension is : 1 

[[1 2 3]
 [4 5 6]] ,the dimension is : 2 

[[['1' '2' '3']
  ['4' '5' '6']]

 [['k' 'r' 'i']
  ['s' 'h' 'n']]] ,the dimension is : 3 



In [11]:
# creating higher dimensions arrays
hdarray = np.array([1,2,3,4,5],ndmin= 5)
print(hdarray)
print("The dimension of",hdarray, "is",hdarray.ndim)

[[[[[1 2 3 4 5]]]]]
The dimension of [[[[[1 2 3 4 5]]]]] is 5


### **NUMPY ARRAYS INDEXING**

In [12]:
arr = np.array([1,2,3,4,5])
print(arr[4])
print(arr[0:3])
print(arr[0:4:2])

5
[1 2 3]
[1 3]


In [13]:
# get the third and fourth array element and add them
a1 = np.array([1,23,4,5])
a2 = np.array([11,33,44,53])
print(a1[2] + a2[3])

57


In [14]:
# get the third and fourth array element and add them in 2d arrays

In [15]:
a = np.array([[1,2,34,5],[4,56,7,29]])
print(a[0,1] + a[1,3])


31


### **NUMPY ARRAY SLICING**

In [16]:
a = [19,27,34,43,52,14,77,45,35,32,22,13,34,46,75,44,542]
print(a[1: 8])
# negative slicing in Numpy arrays 
print(a[-1:-7])

[27, 34, 43, 52, 14, 77, 45]
[]


In [17]:
# step slicing in numpy array
a2 = np.array([1,2,3,4,5,6,7,8,9,5,34,233,213,3,13,24])
print(a2[1:10:2])

[2 4 6 8 5]


### **SLICING IN 2D NUMPY ARRAYS**

In [18]:
a = np.array([[1,2,3,32,4,5],[33,23,21,35,76,89]])
print(a[1,0:4]) # 1 is row value and after comma is the slicing

[33 23 21 35]


In [19]:
print(a[0:2,2])
print(a[1:5,2])

[ 3 21]
[21]


### **DATA TYPES IN NUMPY ARRAY**

In [20]:
'''
i-integer , u = unsigned integer , M = datatime 
f = float, c = comples float , O = object
b = boolean , m = timeDelta , S = string
U = Unicode String , V = fixed Chunks of memory of other type

check datatype = dtype
'''
ar = np.array([1,2,3,4,5], dtype = "S")
print(ar)
print(ar.dtype)



[b'1' b'2' b'3' b'4' b'5']
|S1


### **SHAPE OF ARRAY**

In [21]:
arr = np.array([['a','v','b','s','s','d'],['f','t','i','d','h','g']])
print(arr.shape) # (2,6) 2 is rows and 6 is number of columns
print(arr.dtype)

(2, 6)
<U1


In [22]:
arr = np.array(['a','v','b','s','s','d'],ndmin = 4)
print(arr.shape)
print(arr)

(1, 1, 1, 6)
[[[['a' 'v' 'b' 's' 's' 'd']]]]


### **RESHAPING NUMPY ARRAYS**

In [23]:
# Reshaping from 1 D to 2D
a = np.array([1,2,3,4,5,6,7,8,9,10])
newarr=(a.reshape(5,2)) # 5 is number of dimensions and 2 is the number of values in each dimention
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [24]:
# Reshaping from 1 D to 3D
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=(a.reshape(2,3,2)) # 5 is number of dimensions and 2 is the number of values in each dimention
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [25]:
#convert the Numpy arrays back to 1d array using ravel()
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### **NUMPY AXIS**

In [26]:
'''
AXIS REFERS TO THE DIRECTION ALONG WITH THE OPERATIONS LIKE 
SUM,ADD,DIFFERENCE,PRODUCT ETC ARE PERFORMED

Axis starts from 0 to 1 then ------
Axis 0 is the downward which represent the rows
Axis 1 is the direction across the columns 
'''

'\nAXIS REFERS TO THE DIRECTION ALONG WITH THE OPERATIONS LIKE \nSUM,ADD,DIFFERENCE,PRODUCT ETC ARE PERFORMED\n\nAxis starts from 0 to 1 then ------\nAxis 0 is the downward which represent the rows\nAxis 1 is the direction across the columns \n'

In [27]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
result = np.sum(arr,axis = 0)
print(result)

[ 6  8 10 12]


In [28]:
result = np.sum(arr,axis = 1)
print(result)

[10 26]


In [29]:
result1 = np.mean(arr,axis = 0)
print(result1)
result2 = np.mean(arr,axis = 1)
print(result2)

[3. 4. 5. 6.]
[2.5 6.5]


In [30]:
result3 = np.min(arr,axis = 0)
print(result3)
result4 = np.max(arr,axis = 1)
print(result4)
result5 = np.cumsum(arr,axis = 0)
print(result5)
result6 = np.argmin(arr,axis = 1)
print(result6)
result7 = np.argmax(arr,axis = 0)
print(result7)

[1 2 3 4]
[4 8]
[[ 1  2  3  4]
 [ 6  8 10 12]]
[0 0]
[1 1 1 1]


### **FIND ARRAY USING WHERE(CONDITION)**

In [31]:
findArr = np.array([1,2,3,4,5,6,78,9])
print(np.where(findArr> 7))

(array([6, 7], dtype=int64),)


### **ITERATION IN NUMPY ARRAYS**

In [32]:
arr2 = [[1,2,3,4,5],[6,7,8,9,10]]
for x in arr2:
    print(x)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]


In [33]:
# iterating on each scalar element of the 2d array
aa = [[1, 2, 3, 4, 5], [22, 4, 35, 5, 6]]
for x in aa:
    for y in x:
        print(y)

1
2
3
4
5
22
4
35
5
6


In [34]:
# iterating 3d array elements
arr3d = np.array([[[1,2,3,4],[5,6,7,8],[1,2,3,5],[6,7,8,9]]])
for x in arr3d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
1
2
3
5
6
7
8
9


### **NUMPY ARRAY JOINS**

In [35]:
"""
joining means putting content of two or more arrays in a single array.
"""
# join in 2 arrays :

a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a3 = np.concatenate((a1,a2))

print(a3)

[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
# join 2d arrays
aa1 = np.array([[1,2,3],[4,5,6]])
aa2 = np.array([[11,22,43],[33,44,55]])
aa3 = np.concatenate((aa1,aa2))
print(aa3)

[[ 1  2  3]
 [ 4  5  6]
 [11 22 43]
 [33 44 55]]


### **Joining the array using stack ()**

In [37]:
# Using simple stacking
""" 
the only difference between concatenate and stacking is 
that stacking is done along a new axis
"""
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
arr3 = np.stack((a1,a2),axis = 1) # in rows 
print(arr3)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [38]:
arr4 = np.stack((a1,a2),axis = 0) # in columns
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [39]:
# Stacking using hstack ()-- along rows

a3 = np.array([1,2,3,4,5])
a4 = np.array([6,7,8,9,10])
arr5 = np.hstack((a1,a2)) # along rows 
print(arr5)

[ 1  2  3  4  5  6  7  8  9 10]


In [40]:
# Stacking using vstack() --- along columns
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
arr3 = np.vstack((a1,a2)) # along columns
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
# Stacking using dstack() -- height(depth)
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
arr3 = np.dstack((a1,a2)) #height 
print(arr3)

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


### **NUMPY SEARCHING ARRAYS**


In [42]:
# using Where(condition)
aa = np.array([1,2,54,4,5,7,62,63,82,25])
result = np.where(aa %2 ==0) # pass indexes
print(result)

(array([1, 2, 3, 6, 8], dtype=int64),)


In [43]:
aa2= np.array([1,2,54,4,5,7,62,63,82,25])
result = np.where(aa2 == 7) # pass indexes
print(result)

(array([5], dtype=int64),)


In [44]:
# Using searchsorted() array -- works only with sorted arrays
arr = np.array([41, 52, 24, 55, 26, 17])
arr_sorted = np.sort(arr)  # Sort the array first

# Search for the position of 17
result = np.searchsorted(arr_sorted, 17)
print("Position of 17 from left:", result)

# Search for the position of 17 from the right side
x = np.searchsorted(arr_sorted, 17, side="right")
print("Position of 17 from right:", x)

Position of 17 from left: 0
Position of 17 from right: 1


In [45]:
# multi value search by using searchsorted()

arr= np.array([12,22,44,45,76,87])
x = np.searchsorted(arr,[12,22,44])
print(x)

[0 1 2]


### **NUMPY SORTED ARRAYS**

In [46]:
arr = np.array([219,32,64,98,73,54])
print(np.sort(arr))

[ 32  54  64  73  98 219]


In [47]:
#sorting 2D arrays
aar = np.array([[71,23,33],[21,16,98]])
print(np.sort(aar))

[[23 33 71]
 [16 21 98]]
